<?php

namespace Difane\Bundle\ContentPartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContentPartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentPartRepository extends EntityRepository
{
    public function getContentPart($name)
    {
        try
        {
            return $this->getEntityManager()->createQuery('
                SELECT t FROM DifaneContentPartBundle:ContentPart t                
                WHERE t.name = :name
            ')
            ->setParameter('name', $name)
            ->getSingleResult();
        }
        catch (\Doctrine\ORM\NoResultException $e)
        {
            return null;
        }
    }

    public function getContentParts(array $names)
    {
        try
        {
            $qb = $this->getEntityManager()->createQueryBuilder();

            $qb->select('cp')
                ->from('DifaneContentPartBundle:ContentPart', 'cp')
                ->where($qb->expr()->in('cp.name', $names))
            ;

            return $qb->getQuery()->getResult();            
        }
        catch (\Doctrine\ORM\NoResultException $e)
        {
            return null;
        }
    }
}
