<?php

namespace Difane\Bundle\ContentPartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContentPartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentPartRepository extends EntityRepository
{
    public function getContentPart($name, \Sonata\FormatterBundle\Formatter\Pool $formatterPool = null)
    {
        try
        {
            $result = $this->getEntityManager()->createQuery('
                SELECT t FROM DifaneContentPartBundle:ContentPart t                
                WHERE t.name = :name
            ')
            ->setParameter('name', $name)
            ->getSingleResult();

            $result->setFormatterPool($formatterPool);
            return $result;
        }
        catch (\Doctrine\ORM\NoResultException $e)
        {
            return null;
        }
    }

    public function getContentParts(array $names, \Sonata\FormatterBundle\Formatter\Pool $formatterPool = null)
    {
        try
        {
            $qb = $this->getEntityManager()->createQueryBuilder();

            $qb->select('cp')
                ->from('DifaneContentPartBundle:ContentPart', 'cp')
                ->where($qb->expr()->in('cp.name', $names))
            ;

            $results = $qb->getQuery()->getResult();

            foreach ($results as $result)
            {
                $result->setFormatterPool($formatterPool);
            }

            return $results;
        }
        catch (\Doctrine\ORM\NoResultException $e)
        {
            return null;
        }
    }
}
